version: "3"
services:
  app:
    image: directoryx/php:7.2-opcache-fpm-node10
    container_name: app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/app.ini:/usr/local/etc/php/conf.d/app.ini
    networks:
      - app-network

  db:
    image: postgres:9.6
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: "default"
      POSTGRES_USER: "default"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #Redis Service
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    tty: true
    volumes:
      - ./redis-data:/data
    networks:
      - app-network

  #Redis Service
  phppgadmin:
    image: dockage/phppgadmin
    container_name: phppgadmin
    environment:
      PHP_PG_ADMIN_SERVER_HOST: "db"
      PHP_PG_ADMIN_SERVER_PORT: "5432"
    ports:
      - "8002:80"
    restart: unless-stopped
    tty: true
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local

